vich_uploader:
    db_driver: orm

    mappings:
        deaddrop_image:
            uri_prefix: /images/deaddrops
            upload_destination: '%kernel.project_dir%/public/images/deaddrops'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
